// <auto-generated />
using System;
using MeuMiniMuseu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuMiniMuseu.Migrations
{
    [DbContext(typeof(ArtContext))]
    [Migration("20231216130937_dataseed")]
    partial class dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MeuMiniMuseu.Data.Models.Pintura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnoCriacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pintura");

                    b.HasData(
                        new
                        {
                            Id = 14,
                            AnoCriacao = "1899",
                            Artista = "Alfons Maria Mucha",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFile = "alfons.jpg",
                            Movimento = "Art Noveau",
                            Nome = "Woman with Daisies"
                        },
                        new
                        {
                            Id = 15,
                            AnoCriacao = "1917",
                            Artista = "Hans Larwin",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFile = "death.jpg",
                            Movimento = "Academicismo",
                            Nome = "Death and the Soldier"
                        },
                        new
                        {
                            Id = 16,
                            AnoCriacao = "1879",
                            Artista = "Hanuš Knöchel",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFile = "seashore.jpg",
                            Movimento = "Academicismo",
                            Nome = "On the Seashore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
